### PR TITLE
Add support for DeprecationTime on AMI

### LINKED ISSUE #90: Support for DeprecationTime field on AMIs
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

I would like to be able to set the deprecation time on AMIs, see the what's new post: https://aws.amazon.com/about-aws/whats-new/2021/06/amazon-ec2-adds-new-ami-property-to-flag-outdated-amis/

#### Potential configuration

```
deprecation_time = YYYY-MM-DDTHH:MM:SSZ
```

### LINKED ISSUE #97: Deprecate/ Flag Outdate AMIs - AWS
_This issue was originally opened by @exolain as hashicorp/packer#11098. It was migrated here as a result of the [Packer plugin split](https://github.com/hashicorp/packer/issues/8610#issuecomment-770034737). The original body of the issue is below._

<hr>

Hi all,

Wondering if there was already a feature request to enable the "DeprecateAt" flag as part of the packer AWS amazon-ebs packer builder.
Please see [this documentation ](https://aws.amazon.com/about-aws/whats-new/2021/06/amazon-ec2-adds-new-ami-property-to-flag-outdated-amis/).

I would imagine that a deprecate-at parameter could be configured with the specific date on when the AMI will be considered outdated as part of the AMI buildout.

Let me know your thoughts on this.

### PR DESCRIPTION
**Pull request by meoconbatu**
fixes #97 
fixes #90 

Add EnableDeprecation step in builder.

### CODE REVIEW

**Comment by SwampDragons** [comment]
Thanks so much for this contribution; This looks really solid.

**Comment by meoconbatu** [comment]
I noticed CI run failed for this commit https://github.com/hashicorp/packer-plugin-amazon/commit/3d9288da886f8b77e278d5f2363dc622e0770b00
To fix it, I just need to run  `make generate`
but then I realize that DeprecationTime field is added to other builders too.
So maybe I need to move this EnableDeprecation step to common package (the step is in ebs package now), so other builders can use this step too.
If it is the case, I will create another pull request to fix it.

**Comment by SwampDragons** [comment]
oh shoot how'd I miss that. The ci should have caught that on the branch but I didn't notice a failure when I merged. 

Yes, for now how about you open a PR moving the DeprecationTime field over to the config in eba/builder.go instead of the ami_config, then regenerate docs. If it turns out it's a valid option in the other builders, we can then validate that separately at our leisure.

**Comment by meoconbatu** [comment]
ok I will create another pull request for this.

**Pull request merged**
